//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOn) DeepCopyInto(out *ActiveOn) {
	*out = *in
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = make([]DayOfWeek, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(TimeOfDay)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(TimeOfDay)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOn.
func (in *ActiveOn) DeepCopy() *ActiveOn {
	if in == nil {
		return nil
	}
	out := new(ActiveOn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedNotificationGroupTargets) DeepCopyInto(out *AdvancedNotificationGroupTargets) {
	*out = *in
	if in.AdvancedTargetsSettings != nil {
		in, out := &in.AdvancedTargetsSettings, &out.AdvancedTargetsSettings
		*out = make([]AdvancedTargetsSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedNotificationGroupTargets.
func (in *AdvancedNotificationGroupTargets) DeepCopy() *AdvancedNotificationGroupTargets {
	if in == nil {
		return nil
	}
	out := new(AdvancedNotificationGroupTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdvancedTargetsSettings) DeepCopyInto(out *AdvancedTargetsSettings) {
	*out = *in
	if in.IntegrationId != nil {
		in, out := &in.IntegrationId, &out.IntegrationId
		*out = new(uint32)
		**out = **in
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdvancedTargetsSettings.
func (in *AdvancedTargetsSettings) DeepCopy() *AdvancedTargetsSettings {
	if in == nil {
		return nil
	}
	out := new(AdvancedTargetsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alert) DeepCopyInto(out *Alert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alert.
func (in *Alert) DeepCopy() *Alert {
	if in == nil {
		return nil
	}
	out := new(Alert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Alert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertList) DeepCopyInto(out *AlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Alert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertList.
func (in *AlertList) DeepCopy() *AlertList {
	if in == nil {
		return nil
	}
	out := new(AlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSchedule) DeepCopyInto(out *AlertSchedule) {
	*out = *in
	if in.ActiveOn != nil {
		in, out := &in.ActiveOn, &out.ActiveOn
		*out = new(ActiveOn)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSchedule.
func (in *AlertSchedule) DeepCopy() *AlertSchedule {
	if in == nil {
		return nil
	}
	out := new(AlertSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSpec) DeepCopyInto(out *AlertSpec) {
	*out = *in
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncidentsSettings != nil {
		in, out := &in.IncidentsSettings, &out.IncidentsSettings
		*out = new(IncidentsSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationGroup != nil {
		in, out := &in.NotificationGroup, &out.NotificationGroup
		*out = new(NotificationGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(AlertSchedule)
		(*in).DeepCopyInto(*out)
	}
	in.TypeDefinition.DeepCopyInto(&out.TypeDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSpec.
func (in *AlertSpec) DeepCopy() *AlertSpec {
	if in == nil {
		return nil
	}
	out := new(AlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertStatus) DeepCopyInto(out *AlertStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertStatus.
func (in *AlertStatus) DeepCopy() *AlertStatus {
	if in == nil {
		return nil
	}
	out := new(AlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTypeDefinition) DeepCopyInto(out *AlertTypeDefinition) {
	*out = *in
	if in.LogsImmediate != nil {
		in, out := &in.LogsImmediate, &out.LogsImmediate
		*out = new(LogsImmediate)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsThreshold != nil {
		in, out := &in.LogsThreshold, &out.LogsThreshold
		*out = new(LogsThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsRatioThreshold != nil {
		in, out := &in.LogsRatioThreshold, &out.LogsRatioThreshold
		*out = new(LogsRatioThreshold)
		**out = **in
	}
	if in.LogsTimeRelativeThreshold != nil {
		in, out := &in.LogsTimeRelativeThreshold, &out.LogsTimeRelativeThreshold
		*out = new(LogsTimeRelativeThreshold)
		**out = **in
	}
	if in.MetricThreshold != nil {
		in, out := &in.MetricThreshold, &out.MetricThreshold
		*out = new(MetricThreshold)
		**out = **in
	}
	if in.TracingThreshold != nil {
		in, out := &in.TracingThreshold, &out.TracingThreshold
		*out = new(TracingThreshold)
		**out = **in
	}
	if in.Flow != nil {
		in, out := &in.Flow, &out.Flow
		*out = new(Flow)
		**out = **in
	}
	if in.LogsUnusual != nil {
		in, out := &in.LogsUnusual, &out.LogsUnusual
		*out = new(LogsUnusual)
		**out = **in
	}
	if in.MetricUnusual != nil {
		in, out := &in.MetricUnusual, &out.MetricUnusual
		*out = new(MetricUnusual)
		**out = **in
	}
	if in.LogsNewValue != nil {
		in, out := &in.LogsNewValue, &out.LogsNewValue
		*out = new(LogsNewValue)
		**out = **in
	}
	if in.LogsUniqueCount != nil {
		in, out := &in.LogsUniqueCount, &out.LogsUniqueCount
		*out = new(LogsUniqueCount)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTypeDefinition.
func (in *AlertTypeDefinition) DeepCopy() *AlertTypeDefinition {
	if in == nil {
		return nil
	}
	out := new(AlertTypeDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterType) DeepCopyInto(out *FilterType) {
	*out = *in
	if in.SimpleFilter != nil {
		in, out := &in.SimpleFilter, &out.SimpleFilter
		*out = new(SimpleFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterType.
func (in *FilterType) DeepCopy() *FilterType {
	if in == nil {
		return nil
	}
	out := new(FilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flow.
func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentsSettings) DeepCopyInto(out *IncidentsSettings) {
	*out = *in
	in.RetriggeringPeriod.DeepCopyInto(&out.RetriggeringPeriod)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentsSettings.
func (in *IncidentsSettings) DeepCopy() *IncidentsSettings {
	if in == nil {
		return nil
	}
	out := new(IncidentsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationType) DeepCopyInto(out *IntegrationType) {
	*out = *in
	if in.IntegrationId != nil {
		in, out := &in.IntegrationId, &out.IntegrationId
		*out = new(uint32)
		**out = **in
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationType.
func (in *IntegrationType) DeepCopy() *IntegrationType {
	if in == nil {
		return nil
	}
	out := new(IntegrationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelFilterType) DeepCopyInto(out *LabelFilterType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelFilterType.
func (in *LabelFilterType) DeepCopy() *LabelFilterType {
	if in == nil {
		return nil
	}
	out := new(LabelFilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelFilters) DeepCopyInto(out *LabelFilters) {
	*out = *in
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = make([]LabelFilterType, len(*in))
		copy(*out, *in)
	}
	if in.SubsystemName != nil {
		in, out := &in.SubsystemName, &out.SubsystemName
		*out = make([]LabelFilterType, len(*in))
		copy(*out, *in)
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = make([]LogSeverity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelFilters.
func (in *LabelFilters) DeepCopy() *LabelFilters {
	if in == nil {
		return nil
	}
	out := new(LabelFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsFilter) DeepCopyInto(out *LogsFilter) {
	*out = *in
	in.FilterType.DeepCopyInto(&out.FilterType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsFilter.
func (in *LogsFilter) DeepCopy() *LogsFilter {
	if in == nil {
		return nil
	}
	out := new(LogsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsImmediate) DeepCopyInto(out *LogsImmediate) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsImmediate.
func (in *LogsImmediate) DeepCopy() *LogsImmediate {
	if in == nil {
		return nil
	}
	out := new(LogsImmediate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsNewValue) DeepCopyInto(out *LogsNewValue) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsNewValue.
func (in *LogsNewValue) DeepCopy() *LogsNewValue {
	if in == nil {
		return nil
	}
	out := new(LogsNewValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRatioThreshold) DeepCopyInto(out *LogsRatioThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRatioThreshold.
func (in *LogsRatioThreshold) DeepCopy() *LogsRatioThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsRatioThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThreshold) DeepCopyInto(out *LogsThreshold) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.UndetectedValuesManagement != nil {
		in, out := &in.UndetectedValuesManagement, &out.UndetectedValuesManagement
		*out = new(UndetectedValuesManagement)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsThresholdRule, len(*in))
		copy(*out, *in)
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThreshold.
func (in *LogsThreshold) DeepCopy() *LogsThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThresholdRule) DeepCopyInto(out *LogsThresholdRule) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThresholdRule.
func (in *LogsThresholdRule) DeepCopy() *LogsThresholdRule {
	if in == nil {
		return nil
	}
	out := new(LogsThresholdRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThresholdRuleCondition) DeepCopyInto(out *LogsThresholdRuleCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThresholdRuleCondition.
func (in *LogsThresholdRuleCondition) DeepCopy() *LogsThresholdRuleCondition {
	if in == nil {
		return nil
	}
	out := new(LogsThresholdRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsTimeRelativeThreshold) DeepCopyInto(out *LogsTimeRelativeThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsTimeRelativeThreshold.
func (in *LogsTimeRelativeThreshold) DeepCopy() *LogsTimeRelativeThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsTimeRelativeThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUniqueCount) DeepCopyInto(out *LogsUniqueCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUniqueCount.
func (in *LogsUniqueCount) DeepCopy() *LogsUniqueCount {
	if in == nil {
		return nil
	}
	out := new(LogsUniqueCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUnusual) DeepCopyInto(out *LogsUnusual) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUnusual.
func (in *LogsUnusual) DeepCopy() *LogsUnusual {
	if in == nil {
		return nil
	}
	out := new(LogsUnusual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricThreshold) DeepCopyInto(out *MetricThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricThreshold.
func (in *MetricThreshold) DeepCopy() *MetricThreshold {
	if in == nil {
		return nil
	}
	out := new(MetricThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricUnusual) DeepCopyInto(out *MetricUnusual) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricUnusual.
func (in *MetricUnusual) DeepCopy() *MetricUnusual {
	if in == nil {
		return nil
	}
	out := new(MetricUnusual)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationGroup) DeepCopyInto(out *NotificationGroup) {
	*out = *in
	if in.GroupByFields != nil {
		in, out := &in.GroupByFields, &out.GroupByFields
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Targets.DeepCopyInto(&out.Targets)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationGroup.
func (in *NotificationGroup) DeepCopy() *NotificationGroup {
	if in == nil {
		return nil
	}
	out := new(NotificationGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationGroupTargets) DeepCopyInto(out *NotificationGroupTargets) {
	*out = *in
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(SimpleNotificationGroupTargets)
		(*in).DeepCopyInto(*out)
	}
	if in.Advanced != nil {
		in, out := &in.Advanced, &out.Advanced
		*out = new(AdvancedNotificationGroupTargets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationGroupTargets.
func (in *NotificationGroupTargets) DeepCopy() *NotificationGroupTargets {
	if in == nil {
		return nil
	}
	out := new(NotificationGroupTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetriggeringPeriod) DeepCopyInto(out *RetriggeringPeriod) {
	*out = *in
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetriggeringPeriod.
func (in *RetriggeringPeriod) DeepCopy() *RetriggeringPeriod {
	if in == nil {
		return nil
	}
	out := new(RetriggeringPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleFilter) DeepCopyInto(out *SimpleFilter) {
	*out = *in
	if in.LuceneQuery != nil {
		in, out := &in.LuceneQuery, &out.LuceneQuery
		*out = new(string)
		**out = **in
	}
	if in.LabelFilters != nil {
		in, out := &in.LabelFilters, &out.LabelFilters
		*out = new(LabelFilters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleFilter.
func (in *SimpleFilter) DeepCopy() *SimpleFilter {
	if in == nil {
		return nil
	}
	out := new(SimpleFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SimpleNotificationGroupTargets) DeepCopyInto(out *SimpleNotificationGroupTargets) {
	*out = *in
	if in.Integrations != nil {
		in, out := &in.Integrations, &out.Integrations
		*out = make([]IntegrationType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SimpleNotificationGroupTargets.
func (in *SimpleNotificationGroupTargets) DeepCopy() *SimpleNotificationGroupTargets {
	if in == nil {
		return nil
	}
	out := new(SimpleNotificationGroupTargets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeOfDay) DeepCopyInto(out *TimeOfDay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeOfDay.
func (in *TimeOfDay) DeepCopy() *TimeOfDay {
	if in == nil {
		return nil
	}
	out := new(TimeOfDay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingThreshold) DeepCopyInto(out *TracingThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingThreshold.
func (in *TracingThreshold) DeepCopy() *TracingThreshold {
	if in == nil {
		return nil
	}
	out := new(TracingThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndetectedValuesManagement) DeepCopyInto(out *UndetectedValuesManagement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndetectedValuesManagement.
func (in *UndetectedValuesManagement) DeepCopy() *UndetectedValuesManagement {
	if in == nil {
		return nil
	}
	out := new(UndetectedValuesManagement)
	in.DeepCopyInto(out)
	return out
}
