//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveOn) DeepCopyInto(out *ActiveOn) {
	*out = *in
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = make([]DayOfWeek, len(*in))
		copy(*out, *in)
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = new(TimeOfDay)
		**out = **in
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = new(TimeOfDay)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveOn.
func (in *ActiveOn) DeepCopy() *ActiveOn {
	if in == nil {
		return nil
	}
	out := new(ActiveOn)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Alert) DeepCopyInto(out *Alert) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Alert.
func (in *Alert) DeepCopy() *Alert {
	if in == nil {
		return nil
	}
	out := new(Alert)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Alert) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertList) DeepCopyInto(out *AlertList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Alert, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertList.
func (in *AlertList) DeepCopy() *AlertList {
	if in == nil {
		return nil
	}
	out := new(AlertList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlertList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertOverride) DeepCopyInto(out *AlertOverride) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertOverride.
func (in *AlertOverride) DeepCopy() *AlertOverride {
	if in == nil {
		return nil
	}
	out := new(AlertOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSchedule) DeepCopyInto(out *AlertSchedule) {
	*out = *in
	if in.ActiveOn != nil {
		in, out := &in.ActiveOn, &out.ActiveOn
		*out = new(ActiveOn)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSchedule.
func (in *AlertSchedule) DeepCopy() *AlertSchedule {
	if in == nil {
		return nil
	}
	out := new(AlertSchedule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSpec) DeepCopyInto(out *AlertSpec) {
	*out = *in
	if in.GroupByKeys != nil {
		in, out := &in.GroupByKeys, &out.GroupByKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IncidentsSettings != nil {
		in, out := &in.IncidentsSettings, &out.IncidentsSettings
		*out = new(IncidentsSettings)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationGroup != nil {
		in, out := &in.NotificationGroup, &out.NotificationGroup
		*out = new(NotificationGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationGroupExcess != nil {
		in, out := &in.NotificationGroupExcess, &out.NotificationGroupExcess
		*out = make([]NotificationGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EntityLabels != nil {
		in, out := &in.EntityLabels, &out.EntityLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(AlertSchedule)
		(*in).DeepCopyInto(*out)
	}
	in.TypeDefinition.DeepCopyInto(&out.TypeDefinition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSpec.
func (in *AlertSpec) DeepCopy() *AlertSpec {
	if in == nil {
		return nil
	}
	out := new(AlertSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertStatus) DeepCopyInto(out *AlertStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertStatus.
func (in *AlertStatus) DeepCopy() *AlertStatus {
	if in == nil {
		return nil
	}
	out := new(AlertStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertTypeDefinition) DeepCopyInto(out *AlertTypeDefinition) {
	*out = *in
	if in.LogsImmediate != nil {
		in, out := &in.LogsImmediate, &out.LogsImmediate
		*out = new(LogsImmediate)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsThreshold != nil {
		in, out := &in.LogsThreshold, &out.LogsThreshold
		*out = new(LogsThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsRatioThreshold != nil {
		in, out := &in.LogsRatioThreshold, &out.LogsRatioThreshold
		*out = new(LogsRatioThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsTimeRelativeThreshold != nil {
		in, out := &in.LogsTimeRelativeThreshold, &out.LogsTimeRelativeThreshold
		*out = new(LogsTimeRelativeThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricThreshold != nil {
		in, out := &in.MetricThreshold, &out.MetricThreshold
		*out = new(MetricThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.TracingThreshold != nil {
		in, out := &in.TracingThreshold, &out.TracingThreshold
		*out = new(TracingThreshold)
		(*in).DeepCopyInto(*out)
	}
	if in.Flow != nil {
		in, out := &in.Flow, &out.Flow
		*out = new(Flow)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsAnomaly != nil {
		in, out := &in.LogsAnomaly, &out.LogsAnomaly
		*out = new(LogsAnomaly)
		(*in).DeepCopyInto(*out)
	}
	if in.MetricAnomaly != nil {
		in, out := &in.MetricAnomaly, &out.MetricAnomaly
		*out = new(MetricAnomaly)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsNewValue != nil {
		in, out := &in.LogsNewValue, &out.LogsNewValue
		*out = new(LogsNewValue)
		(*in).DeepCopyInto(*out)
	}
	if in.LogsUniqueCount != nil {
		in, out := &in.LogsUniqueCount, &out.LogsUniqueCount
		*out = new(LogsUniqueCount)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertTypeDefinition.
func (in *AlertTypeDefinition) DeepCopy() *AlertTypeDefinition {
	if in == nil {
		return nil
	}
	out := new(AlertTypeDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Flow) DeepCopyInto(out *Flow) {
	*out = *in
	if in.Stages != nil {
		in, out := &in.Stages, &out.Stages
		*out = make([]FlowStage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Flow.
func (in *Flow) DeepCopy() *Flow {
	if in == nil {
		return nil
	}
	out := new(Flow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowStage) DeepCopyInto(out *FlowStage) {
	*out = *in
	in.FlowStagesType.DeepCopyInto(&out.FlowStagesType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowStage.
func (in *FlowStage) DeepCopy() *FlowStage {
	if in == nil {
		return nil
	}
	out := new(FlowStage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowStageGroup) DeepCopyInto(out *FlowStageGroup) {
	*out = *in
	if in.AlertDefs != nil {
		in, out := &in.AlertDefs, &out.AlertDefs
		*out = make([]FlowStagesGroupsAlertDefs, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowStageGroup.
func (in *FlowStageGroup) DeepCopy() *FlowStageGroup {
	if in == nil {
		return nil
	}
	out := new(FlowStageGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowStagesGroupsAlertDefs) DeepCopyInto(out *FlowStagesGroupsAlertDefs) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowStagesGroupsAlertDefs.
func (in *FlowStagesGroupsAlertDefs) DeepCopy() *FlowStagesGroupsAlertDefs {
	if in == nil {
		return nil
	}
	out := new(FlowStagesGroupsAlertDefs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FlowStagesType) DeepCopyInto(out *FlowStagesType) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]FlowStageGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FlowStagesType.
func (in *FlowStagesType) DeepCopy() *FlowStagesType {
	if in == nil {
		return nil
	}
	out := new(FlowStagesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncidentsSettings) DeepCopyInto(out *IncidentsSettings) {
	*out = *in
	in.RetriggeringPeriod.DeepCopyInto(&out.RetriggeringPeriod)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncidentsSettings.
func (in *IncidentsSettings) DeepCopy() *IncidentsSettings {
	if in == nil {
		return nil
	}
	out := new(IncidentsSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntegrationType) DeepCopyInto(out *IntegrationType) {
	*out = *in
	if in.IntegrationId != nil {
		in, out := &in.IntegrationId, &out.IntegrationId
		*out = new(uint32)
		**out = **in
	}
	if in.Recipients != nil {
		in, out := &in.Recipients, &out.Recipients
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntegrationType.
func (in *IntegrationType) DeepCopy() *IntegrationType {
	if in == nil {
		return nil
	}
	out := new(IntegrationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelFilterType) DeepCopyInto(out *LabelFilterType) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelFilterType.
func (in *LabelFilterType) DeepCopy() *LabelFilterType {
	if in == nil {
		return nil
	}
	out := new(LabelFilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LabelFilters) DeepCopyInto(out *LabelFilters) {
	*out = *in
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = make([]LabelFilterType, len(*in))
		copy(*out, *in)
	}
	if in.SubsystemName != nil {
		in, out := &in.SubsystemName, &out.SubsystemName
		*out = make([]LabelFilterType, len(*in))
		copy(*out, *in)
	}
	if in.Severity != nil {
		in, out := &in.Severity, &out.Severity
		*out = make([]LogSeverity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LabelFilters.
func (in *LabelFilters) DeepCopy() *LabelFilters {
	if in == nil {
		return nil
	}
	out := new(LabelFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsAnomaly) DeepCopyInto(out *LogsAnomaly) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsAnomalyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsAnomaly.
func (in *LogsAnomaly) DeepCopy() *LogsAnomaly {
	if in == nil {
		return nil
	}
	out := new(LogsAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsAnomalyCondition) DeepCopyInto(out *LogsAnomalyCondition) {
	*out = *in
	out.MinimumThreshold = in.MinimumThreshold.DeepCopy()
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsAnomalyCondition.
func (in *LogsAnomalyCondition) DeepCopy() *LogsAnomalyCondition {
	if in == nil {
		return nil
	}
	out := new(LogsAnomalyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsAnomalyRule) DeepCopyInto(out *LogsAnomalyRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsAnomalyRule.
func (in *LogsAnomalyRule) DeepCopy() *LogsAnomalyRule {
	if in == nil {
		return nil
	}
	out := new(LogsAnomalyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsFilter) DeepCopyInto(out *LogsFilter) {
	*out = *in
	in.SimpleFilter.DeepCopyInto(&out.SimpleFilter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsFilter.
func (in *LogsFilter) DeepCopy() *LogsFilter {
	if in == nil {
		return nil
	}
	out := new(LogsFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsImmediate) DeepCopyInto(out *LogsImmediate) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsImmediate.
func (in *LogsImmediate) DeepCopy() *LogsImmediate {
	if in == nil {
		return nil
	}
	out := new(LogsImmediate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsNewValue) DeepCopyInto(out *LogsNewValue) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsNewValueRule, len(*in))
		copy(*out, *in)
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsNewValue.
func (in *LogsNewValue) DeepCopy() *LogsNewValue {
	if in == nil {
		return nil
	}
	out := new(LogsNewValue)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsNewValueRule) DeepCopyInto(out *LogsNewValueRule) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsNewValueRule.
func (in *LogsNewValueRule) DeepCopy() *LogsNewValueRule {
	if in == nil {
		return nil
	}
	out := new(LogsNewValueRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsNewValueRuleCondition) DeepCopyInto(out *LogsNewValueRuleCondition) {
	*out = *in
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsNewValueRuleCondition.
func (in *LogsNewValueRuleCondition) DeepCopy() *LogsNewValueRuleCondition {
	if in == nil {
		return nil
	}
	out := new(LogsNewValueRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsNewValueTimeWindow) DeepCopyInto(out *LogsNewValueTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsNewValueTimeWindow.
func (in *LogsNewValueTimeWindow) DeepCopy() *LogsNewValueTimeWindow {
	if in == nil {
		return nil
	}
	out := new(LogsNewValueTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRatioCondition) DeepCopyInto(out *LogsRatioCondition) {
	*out = *in
	out.Threshold = in.Threshold.DeepCopy()
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRatioCondition.
func (in *LogsRatioCondition) DeepCopy() *LogsRatioCondition {
	if in == nil {
		return nil
	}
	out := new(LogsRatioCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRatioThreshold) DeepCopyInto(out *LogsRatioThreshold) {
	*out = *in
	in.Numerator.DeepCopyInto(&out.Numerator)
	in.Denominator.DeepCopyInto(&out.Denominator)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsRatioThresholdRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRatioThreshold.
func (in *LogsRatioThreshold) DeepCopy() *LogsRatioThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsRatioThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRatioThresholdRule) DeepCopyInto(out *LogsRatioThresholdRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Override = in.Override
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRatioThresholdRule.
func (in *LogsRatioThresholdRule) DeepCopy() *LogsRatioThresholdRule {
	if in == nil {
		return nil
	}
	out := new(LogsRatioThresholdRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsRatioTimeWindow) DeepCopyInto(out *LogsRatioTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsRatioTimeWindow.
func (in *LogsRatioTimeWindow) DeepCopy() *LogsRatioTimeWindow {
	if in == nil {
		return nil
	}
	out := new(LogsRatioTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsSimpleFilter) DeepCopyInto(out *LogsSimpleFilter) {
	*out = *in
	if in.LuceneQuery != nil {
		in, out := &in.LuceneQuery, &out.LuceneQuery
		*out = new(string)
		**out = **in
	}
	if in.LabelFilters != nil {
		in, out := &in.LabelFilters, &out.LabelFilters
		*out = new(LabelFilters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsSimpleFilter.
func (in *LogsSimpleFilter) DeepCopy() *LogsSimpleFilter {
	if in == nil {
		return nil
	}
	out := new(LogsSimpleFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThreshold) DeepCopyInto(out *LogsThreshold) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.UndetectedValuesManagement != nil {
		in, out := &in.UndetectedValuesManagement, &out.UndetectedValuesManagement
		*out = new(UndetectedValuesManagement)
		**out = **in
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsThresholdRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThreshold.
func (in *LogsThreshold) DeepCopy() *LogsThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThresholdRule) DeepCopyInto(out *LogsThresholdRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Override = in.Override
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThresholdRule.
func (in *LogsThresholdRule) DeepCopy() *LogsThresholdRule {
	if in == nil {
		return nil
	}
	out := new(LogsThresholdRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsThresholdRuleCondition) DeepCopyInto(out *LogsThresholdRuleCondition) {
	*out = *in
	out.TimeWindow = in.TimeWindow
	out.Threshold = in.Threshold.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsThresholdRuleCondition.
func (in *LogsThresholdRuleCondition) DeepCopy() *LogsThresholdRuleCondition {
	if in == nil {
		return nil
	}
	out := new(LogsThresholdRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsTimeRelativeCondition) DeepCopyInto(out *LogsTimeRelativeCondition) {
	*out = *in
	out.Threshold = in.Threshold.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsTimeRelativeCondition.
func (in *LogsTimeRelativeCondition) DeepCopy() *LogsTimeRelativeCondition {
	if in == nil {
		return nil
	}
	out := new(LogsTimeRelativeCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsTimeRelativeRule) DeepCopyInto(out *LogsTimeRelativeRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Override = in.Override
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsTimeRelativeRule.
func (in *LogsTimeRelativeRule) DeepCopy() *LogsTimeRelativeRule {
	if in == nil {
		return nil
	}
	out := new(LogsTimeRelativeRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsTimeRelativeThreshold) DeepCopyInto(out *LogsTimeRelativeThreshold) {
	*out = *in
	in.LogsFilter.DeepCopyInto(&out.LogsFilter)
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsTimeRelativeRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UndetectedValuesManagement != nil {
		in, out := &in.UndetectedValuesManagement, &out.UndetectedValuesManagement
		*out = new(UndetectedValuesManagement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsTimeRelativeThreshold.
func (in *LogsTimeRelativeThreshold) DeepCopy() *LogsTimeRelativeThreshold {
	if in == nil {
		return nil
	}
	out := new(LogsTimeRelativeThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsTimeWindow) DeepCopyInto(out *LogsTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsTimeWindow.
func (in *LogsTimeWindow) DeepCopy() *LogsTimeWindow {
	if in == nil {
		return nil
	}
	out := new(LogsTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUniqueCount) DeepCopyInto(out *LogsUniqueCount) {
	*out = *in
	if in.LogsFilter != nil {
		in, out := &in.LogsFilter, &out.LogsFilter
		*out = new(LogsFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]LogsUniqueCountRule, len(*in))
		copy(*out, *in)
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.MaxUniqueCountPerGroupByKey != nil {
		in, out := &in.MaxUniqueCountPerGroupByKey, &out.MaxUniqueCountPerGroupByKey
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUniqueCount.
func (in *LogsUniqueCount) DeepCopy() *LogsUniqueCount {
	if in == nil {
		return nil
	}
	out := new(LogsUniqueCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUniqueCountCondition) DeepCopyInto(out *LogsUniqueCountCondition) {
	*out = *in
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUniqueCountCondition.
func (in *LogsUniqueCountCondition) DeepCopy() *LogsUniqueCountCondition {
	if in == nil {
		return nil
	}
	out := new(LogsUniqueCountCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUniqueCountRule) DeepCopyInto(out *LogsUniqueCountRule) {
	*out = *in
	out.Condition = in.Condition
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUniqueCountRule.
func (in *LogsUniqueCountRule) DeepCopy() *LogsUniqueCountRule {
	if in == nil {
		return nil
	}
	out := new(LogsUniqueCountRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogsUniqueCountTimeWindow) DeepCopyInto(out *LogsUniqueCountTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogsUniqueCountTimeWindow.
func (in *LogsUniqueCountTimeWindow) DeepCopy() *LogsUniqueCountTimeWindow {
	if in == nil {
		return nil
	}
	out := new(LogsUniqueCountTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAnomaly) DeepCopyInto(out *MetricAnomaly) {
	*out = *in
	out.MetricFilter = in.MetricFilter
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MetricAnomalyRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAnomaly.
func (in *MetricAnomaly) DeepCopy() *MetricAnomaly {
	if in == nil {
		return nil
	}
	out := new(MetricAnomaly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAnomalyCondition) DeepCopyInto(out *MetricAnomalyCondition) {
	*out = *in
	out.Threshold = in.Threshold.DeepCopy()
	out.OfTheLast = in.OfTheLast
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAnomalyCondition.
func (in *MetricAnomalyCondition) DeepCopy() *MetricAnomalyCondition {
	if in == nil {
		return nil
	}
	out := new(MetricAnomalyCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricAnomalyRule) DeepCopyInto(out *MetricAnomalyRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricAnomalyRule.
func (in *MetricAnomalyRule) DeepCopy() *MetricAnomalyRule {
	if in == nil {
		return nil
	}
	out := new(MetricAnomalyRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricFilter) DeepCopyInto(out *MetricFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricFilter.
func (in *MetricFilter) DeepCopy() *MetricFilter {
	if in == nil {
		return nil
	}
	out := new(MetricFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricMissingValues) DeepCopyInto(out *MetricMissingValues) {
	*out = *in
	if in.ReplaceWithZero != nil {
		in, out := &in.ReplaceWithZero, &out.ReplaceWithZero
		*out = new(bool)
		**out = **in
	}
	if in.MinNonNullValuesPct != nil {
		in, out := &in.MinNonNullValuesPct, &out.MinNonNullValuesPct
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricMissingValues.
func (in *MetricMissingValues) DeepCopy() *MetricMissingValues {
	if in == nil {
		return nil
	}
	out := new(MetricMissingValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricThreshold) DeepCopyInto(out *MetricThreshold) {
	*out = *in
	out.MetricFilter = in.MetricFilter
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MetricThresholdRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.MissingValues.DeepCopyInto(&out.MissingValues)
	if in.UndetectedValuesManagement != nil {
		in, out := &in.UndetectedValuesManagement, &out.UndetectedValuesManagement
		*out = new(UndetectedValuesManagement)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricThreshold.
func (in *MetricThreshold) DeepCopy() *MetricThreshold {
	if in == nil {
		return nil
	}
	out := new(MetricThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricThresholdRule) DeepCopyInto(out *MetricThresholdRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
	out.Override = in.Override
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricThresholdRule.
func (in *MetricThresholdRule) DeepCopy() *MetricThresholdRule {
	if in == nil {
		return nil
	}
	out := new(MetricThresholdRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricThresholdRuleCondition) DeepCopyInto(out *MetricThresholdRuleCondition) {
	*out = *in
	out.Threshold = in.Threshold.DeepCopy()
	out.OfTheLast = in.OfTheLast
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricThresholdRuleCondition.
func (in *MetricThresholdRuleCondition) DeepCopy() *MetricThresholdRuleCondition {
	if in == nil {
		return nil
	}
	out := new(MetricThresholdRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricTimeWindow) DeepCopyInto(out *MetricTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricTimeWindow.
func (in *MetricTimeWindow) DeepCopy() *MetricTimeWindow {
	if in == nil {
		return nil
	}
	out := new(MetricTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NotificationGroup) DeepCopyInto(out *NotificationGroup) {
	*out = *in
	if in.GroupByKeys != nil {
		in, out := &in.GroupByKeys, &out.GroupByKeys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Webhooks != nil {
		in, out := &in.Webhooks, &out.Webhooks
		*out = make([]WebhookSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NotificationGroup.
func (in *NotificationGroup) DeepCopy() *NotificationGroup {
	if in == nil {
		return nil
	}
	out := new(NotificationGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetriggeringPeriod) DeepCopyInto(out *RetriggeringPeriod) {
	*out = *in
	if in.Minutes != nil {
		in, out := &in.Minutes, &out.Minutes
		*out = new(uint32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetriggeringPeriod.
func (in *RetriggeringPeriod) DeepCopy() *RetriggeringPeriod {
	if in == nil {
		return nil
	}
	out := new(RetriggeringPeriod)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingFilter) DeepCopyInto(out *TracingFilter) {
	*out = *in
	if in.Simple != nil {
		in, out := &in.Simple, &out.Simple
		*out = new(TracingSimpleFilter)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingFilter.
func (in *TracingFilter) DeepCopy() *TracingFilter {
	if in == nil {
		return nil
	}
	out := new(TracingFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingFilterType) DeepCopyInto(out *TracingFilterType) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingFilterType.
func (in *TracingFilterType) DeepCopy() *TracingFilterType {
	if in == nil {
		return nil
	}
	out := new(TracingFilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingLabelFilters) DeepCopyInto(out *TracingLabelFilters) {
	*out = *in
	if in.ApplicationName != nil {
		in, out := &in.ApplicationName, &out.ApplicationName
		*out = make([]TracingFilterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubsystemName != nil {
		in, out := &in.SubsystemName, &out.SubsystemName
		*out = make([]TracingFilterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ServiceName != nil {
		in, out := &in.ServiceName, &out.ServiceName
		*out = make([]TracingFilterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OperationName != nil {
		in, out := &in.OperationName, &out.OperationName
		*out = make([]TracingFilterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SpanFields != nil {
		in, out := &in.SpanFields, &out.SpanFields
		*out = make([]TracingSpanFieldsFilterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingLabelFilters.
func (in *TracingLabelFilters) DeepCopy() *TracingLabelFilters {
	if in == nil {
		return nil
	}
	out := new(TracingLabelFilters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingSimpleFilter) DeepCopyInto(out *TracingSimpleFilter) {
	*out = *in
	if in.TracingLabelFilters != nil {
		in, out := &in.TracingLabelFilters, &out.TracingLabelFilters
		*out = new(TracingLabelFilters)
		(*in).DeepCopyInto(*out)
	}
	if in.LatencyThresholdMs != nil {
		in, out := &in.LatencyThresholdMs, &out.LatencyThresholdMs
		*out = new(uint64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingSimpleFilter.
func (in *TracingSimpleFilter) DeepCopy() *TracingSimpleFilter {
	if in == nil {
		return nil
	}
	out := new(TracingSimpleFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingSpanFieldsFilterType) DeepCopyInto(out *TracingSpanFieldsFilterType) {
	*out = *in
	in.FilterType.DeepCopyInto(&out.FilterType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingSpanFieldsFilterType.
func (in *TracingSpanFieldsFilterType) DeepCopy() *TracingSpanFieldsFilterType {
	if in == nil {
		return nil
	}
	out := new(TracingSpanFieldsFilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingThreshold) DeepCopyInto(out *TracingThreshold) {
	*out = *in
	if in.TracingFilter != nil {
		in, out := &in.TracingFilter, &out.TracingFilter
		*out = new(TracingFilter)
		(*in).DeepCopyInto(*out)
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]TracingThresholdRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotificationPayloadFilter != nil {
		in, out := &in.NotificationPayloadFilter, &out.NotificationPayloadFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingThreshold.
func (in *TracingThreshold) DeepCopy() *TracingThreshold {
	if in == nil {
		return nil
	}
	out := new(TracingThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingThresholdRule) DeepCopyInto(out *TracingThresholdRule) {
	*out = *in
	in.Condition.DeepCopyInto(&out.Condition)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingThresholdRule.
func (in *TracingThresholdRule) DeepCopy() *TracingThresholdRule {
	if in == nil {
		return nil
	}
	out := new(TracingThresholdRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingThresholdRuleCondition) DeepCopyInto(out *TracingThresholdRuleCondition) {
	*out = *in
	out.SpanAmount = in.SpanAmount.DeepCopy()
	out.TimeWindow = in.TimeWindow
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingThresholdRuleCondition.
func (in *TracingThresholdRuleCondition) DeepCopy() *TracingThresholdRuleCondition {
	if in == nil {
		return nil
	}
	out := new(TracingThresholdRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TracingTimeWindow) DeepCopyInto(out *TracingTimeWindow) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TracingTimeWindow.
func (in *TracingTimeWindow) DeepCopy() *TracingTimeWindow {
	if in == nil {
		return nil
	}
	out := new(TracingTimeWindow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UndetectedValuesManagement) DeepCopyInto(out *UndetectedValuesManagement) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UndetectedValuesManagement.
func (in *UndetectedValuesManagement) DeepCopy() *UndetectedValuesManagement {
	if in == nil {
		return nil
	}
	out := new(UndetectedValuesManagement)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebhookSettings) DeepCopyInto(out *WebhookSettings) {
	*out = *in
	in.RetriggeringPeriod.DeepCopyInto(&out.RetriggeringPeriod)
	in.Integration.DeepCopyInto(&out.Integration)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebhookSettings.
func (in *WebhookSettings) DeepCopy() *WebhookSettings {
	if in == nil {
		return nil
	}
	out := new(WebhookSettings)
	in.DeepCopyInto(out)
	return out
}
