{{- if .Values.alerts.enabled }}
apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
  name: workqueue-depth-growth
  namespace: coralogix-operator
spec:
  name: workqueue-depth-growth alert
  description: Queue backlog growing - Work-queue depth keeps climbing, showing the controller can’t process events as fast as they arrive.
  priority: p4
  entityLabels:
    {{- toYaml .Values.alerts.alert_workqueue_depth_growth.entityLabels | nindent 4 }}
  alertType:
    metricThreshold:
      metricFilter:
        promql: |
          sum(workqueue_depth{pod=~"{{include coralogixOperator.fullname . }}.*"}) > 0.3
      missingValues:
        minNonNullValuesPct: 60
      rules:
        - condition:
            threshold: "0.3"
            forOverPct: 20
            ofTheLast:
              specificValue: 15m
            conditionType: moreThan
{{- end }}