apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-operator-controller-manager
  namespace: default # replace with your namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: manager
          image:
          command:
            - /manager
          args:
            - --enable-leader-election
            - --metrics-bind-address=:8080
            - --health-probe-bind-address=:8081
            - --webhook-port=9443  # Webhook listens on this port
          ports:
            - containerPort: 9443
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
