---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lVVGxDdXhOdXdYM1N1QmVBeHFlalQzR3grU3lzd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkMlZpYUc5dmF5MXpaWEoyYVdObExtTnZjbUZzYjJkcGVDMXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqTUI0WERUSTBNVEF4TkRBNU5UVXdORm9YRFRJMU1UQXhOREE1TlRVd05Gb3dPREUyCk1EUUdBMVVFQXd3dGQyVmlhRzl2YXkxelpYSjJhV05sTG1OdmNtRnNiMmRwZUMxdmNHVnlZWFJ2Y2kxemVYTjAKWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTBOajFQQWRrWnJDYwpVUXRHcW9mbEFrVXpVODZnUTVrSGQ0VUZ1S0RtdkRjQ2FUSmcwYnVZZVhSL0ZhYlh1clhsdWMrRTg1YjVFc3RRCmRZbm9rdUVjM25QcHdrMkwvUUJuNndQQkkzU1g1d0ZKaExBd1Bkck5DQWtKNVRkWkg2cThJdW5ScHVEY3JMaFEKT1hzMzF0VitpU2N6T0pvZFpKeThrU0hGWXVzVXo0L3VvaHBsVXh2THdJUUtUWnlabVVnT3pNUm93NUZYd0FHVApWV29Jd1lIT09nQkh0bUF4d0swRmI0TVdNbXVhaE8yK1NjVnlRa0FVWXRwaFVWQnN0SHJpYzkrZ1Baa3NudHdGCmZCYjZIaldDMTFzSnJMVmZTVC9aSmpZTVhZVjg2TGtxVDNQM3o5Mk9hZzM1V0U4QXJXNktBSFdnZWNMRmNkMkEKMUNuc3p2Q1VlUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVOU9zTUQwMjZXQlJJSTMzUmViZFM1NUhnR3Q4dwpId1lEVlIwakJCZ3dGb0FVOU9zTUQwMjZXQlJJSTMzUmViZFM1NUhnR3Q4d0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFNT05kMnRZQzVGQ3BEYm1KNzVnMTBvOSs2NHJIZnpHbVhvRXIKQS81MFkvRVdtQ2lzbllFWWZsSWU5cXdQT3BJZDY0LytZMjlXeS9JMHlDems2ZW1sbzJnKzYrcjFGbm04SWFaUQpTcFJPR0NKVjdzS3dVNXBMMVFXM1ZESGVlYUM0S05EM1A0cE9QL0lETHg5VUtjN3JoUWNqMVlIVlI1dkNjZC9UCjYzNElXRmd2ZUFETlZLbU9NTENIK3psK04yZXQ4aUhpRmhtTExIc216YWdXeWpRSlBIdWxkK3NwY1hvMnl5dDIKbFBHTnVjWUc1c0Z6MHUvSk43VkRoaWpJeFM2YVE2azYrdVpjOXhqa0JxQTRBcEJ2aFJVOGFmWUxPUmJCQ21TNQpCQklWeno1bmxSNmtLTnNEdDJBeVpwN2FCeExybWdYb0VCTC90dnZUdE1pdTdNeGRCQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook-service
      namespace: coralogix-operator-system
      path: /validate-coralogix-com-v1alpha1-outboundwebhook
  failurePolicy: Fail
  name: outboundwebhook.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - outboundwebhooks
  sideEffects: None
