---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lVUjdTMG9IUGs3VmVqODRSUk1sVjg3Mlc4VE93d0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkMlZpYUc5dmF5MXpaWEoyYVdObExtTnZjbUZzYjJkcGVDMXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqTUI0WERUSTBNVEl4T1RBNE5UUXdOVm9YRFRJMU1USXhPVEE0TlRRd05Wb3dPREUyCk1EUUdBMVVFQXd3dGQyVmlhRzl2YXkxelpYSjJhV05sTG1OdmNtRnNiMmRwZUMxdmNHVnlZWFJ2Y2kxemVYTjAKWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBBeGM4RlFCRnQ0UQo0TjlxYXhvL1BWSmRsRVlDYUxRSXZSMVF4SVVHUHN1eG5RMGwxTVBIZnpvN3RBbzlvR0ptSUR0Z211T29kUnFxCkt4WXg2eXNkbXorWmFFT1BSMkhiWjFWVW1PYlNVZGZ3UWlSTTlSMjBha1BZZlB6ZWFVMktpYmZ1bkZVWUV1UmoKTVI0bnRsb3dqYmRBa1FtWHA0WWJTT0ErYndtb2xHTndYT2NqcVo0am9zTVFmc003MXhaMVhPVTM0VU5zNGpiSAppcHRkcjk0QXZIQkZTNzFEcU8vM3gwZXZHMUxKNUhHMjlTaldsYlJtZXVvdDNkOWVONzlEOTM3UDRFb1UyOXlGCndLZlRQREtYZCtUQm5CNmZPWllsV1JQc3VseWlKSFhmWkVMVHloMFR0VUxIYlRUR3E4Qmhvb0U5WjlRVXc5SnoKZVhFRVAxOWlVUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVZWF1SFk5eGZ1WlBkTUF0aTFJRVJ1bEJGOGVzdwpId1lEVlIwakJCZ3dGb0FVZWF1SFk5eGZ1WlBkTUF0aTFJRVJ1bEJGOGVzd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXdHpjdXVjZHVDeEdpTHZYTy9MaUNqdjRwRm1tOVZkRk90R20Kb0VUbHNHRU9VZGVYSG1NSGc1MmRvZTZSRE45dmExZzdwbzl3eGVMMThMeCtiUCswQ1hLU29QbEhnZ1pLL25CdwozNEFHbGtvQ1Bocy94T0ZHNFQzcEUySmlQc3hhWCsvOVdGdXpxd1p3ZUpaVEVNeS9MK1EvMmlZM29nTDZCS2JkClN5WkU0eVNCK3ViNUlMcGUvaU1lUE9nK0lEU2U0dExEVXhwL2lIQWZla1FQQjd0dkRwTUJVWHkwdmV5VjUrZisKaUxLYTZaUTNCOThvajNiR21ENk1BZkRlU2pLakNLak5vTGIrL1hUajhNcFJsbzdHMmsvSnk0bTZSY3htTHVNcAphT2kvcUxrTzd4enpuVlY2WFR3bGZOejVuazJaWlhZVW9WY0taWm9nN1JJZ1lPaU5Qdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook-service
      namespace: coralogix-operator-system
      path: /validate-coralogix-com-v1alpha1-outboundwebhook
  failurePolicy: Fail
  name: voutboundwebhook-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - outboundwebhooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lVUjdTMG9IUGs3VmVqODRSUk1sVjg3Mlc4VE93d0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkMlZpYUc5dmF5MXpaWEoyYVdObExtTnZjbUZzYjJkcGVDMXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqTUI0WERUSTBNVEl4T1RBNE5UUXdOVm9YRFRJMU1USXhPVEE0TlRRd05Wb3dPREUyCk1EUUdBMVVFQXd3dGQyVmlhRzl2YXkxelpYSjJhV05sTG1OdmNtRnNiMmRwZUMxdmNHVnlZWFJ2Y2kxemVYTjAKWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXBBeGM4RlFCRnQ0UQo0TjlxYXhvL1BWSmRsRVlDYUxRSXZSMVF4SVVHUHN1eG5RMGwxTVBIZnpvN3RBbzlvR0ptSUR0Z211T29kUnFxCkt4WXg2eXNkbXorWmFFT1BSMkhiWjFWVW1PYlNVZGZ3UWlSTTlSMjBha1BZZlB6ZWFVMktpYmZ1bkZVWUV1UmoKTVI0bnRsb3dqYmRBa1FtWHA0WWJTT0ErYndtb2xHTndYT2NqcVo0am9zTVFmc003MXhaMVhPVTM0VU5zNGpiSAppcHRkcjk0QXZIQkZTNzFEcU8vM3gwZXZHMUxKNUhHMjlTaldsYlJtZXVvdDNkOWVONzlEOTM3UDRFb1UyOXlGCndLZlRQREtYZCtUQm5CNmZPWllsV1JQc3VseWlKSFhmWkVMVHloMFR0VUxIYlRUR3E4Qmhvb0U5WjlRVXc5SnoKZVhFRVAxOWlVUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVZWF1SFk5eGZ1WlBkTUF0aTFJRVJ1bEJGOGVzdwpId1lEVlIwakJCZ3dGb0FVZWF1SFk5eGZ1WlBkTUF0aTFJRVJ1bEJGOGVzd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXdHpjdXVjZHVDeEdpTHZYTy9MaUNqdjRwRm1tOVZkRk90R20Kb0VUbHNHRU9VZGVYSG1NSGc1MmRvZTZSRE45dmExZzdwbzl3eGVMMThMeCtiUCswQ1hLU29QbEhnZ1pLL25CdwozNEFHbGtvQ1Bocy94T0ZHNFQzcEUySmlQc3hhWCsvOVdGdXpxd1p3ZUpaVEVNeS9MK1EvMmlZM29nTDZCS2JkClN5WkU0eVNCK3ViNUlMcGUvaU1lUE9nK0lEU2U0dExEVXhwL2lIQWZla1FQQjd0dkRwTUJVWHkwdmV5VjUrZisKaUxLYTZaUTNCOThvajNiR21ENk1BZkRlU2pLakNLak5vTGIrL1hUajhNcFJsbzdHMmsvSnk0bTZSY3htTHVNcAphT2kvcUxrTzd4enpuVlY2WFR3bGZOejVuazJaWlhZVW9WY0taWm9nN1JJZ1lPaU5Qdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook-service
      namespace: coralogix-operator-system
      path: /validate-coralogix-com-v1alpha1-rulegroup
  failurePolicy: Fail
  name: vrulegroup-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rulegroups
  sideEffects: None
