---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURVVENDQWptZ0F3SUJBZ0lVSTk1dWNaWDk3cUd5ZHRtUnZQenJyeFBpTFRVd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkMlZpYUc5dmF5MXpaWEoyYVdObExtTnZjbUZzYjJkcGVDMXZjR1Z5WVhSdgpjaTF6ZVhOMFpXMHVjM1pqTUI0WERUSTBNVEF4TkRFeU1qVTFNRm9YRFRJMU1UQXhOREV5TWpVMU1Gb3dPREUyCk1EUUdBMVVFQXd3dGQyVmlhRzl2YXkxelpYSjJhV05sTG1OdmNtRnNiMmRwZUMxdmNHVnlZWFJ2Y2kxemVYTjAKWlcwdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW9GMU1sSStYNTFaWQpOOEdOLzk2dkhzY3hta0tyRy9OcU5sdnN2aFRYS09VbGdsRUJlY3ZZclhIWVFiQUhiNUR6dkMxeHVtRlBKcUF2CnVrblZkZ0xWL2FXelJMamtlYkdDVjBSaXBhSUN3YWJTNSt3MTlnZFAyaHVLRU8rTDBXck45bHMrbVdMNms5cHIKK01hOVN3ZlNrMkx0eENNVnZBMlF0OVV5b3h3aVRjTFNCaGd0QnVwRGtPV2RyMGR6a3dic1dpcDBLNHRHbDEwZAo2OWo0QUlKUXJ6QVppRUkwQUppSWFJODM0emlzdlBpVWl1a2ZVS2hyZlJ0bkxHZXkvQTVwdmNYbE5qYlV0UUhvCiszREY4OW8yVlYzWHBrdzVQZUl1R1NzNW1UZ0JUZGdHazZOWWhpaHJuYjh2WmVkV0svZVlBZGxoU292czZ2ZmYKaXB1MXJpWFNUUUlEQVFBQm8xTXdVVEFkQmdOVkhRNEVGZ1FVMkxWWGtXNkpuY2ZKQkxocHEwNG1EWEdNbnlvdwpId1lEVlIwakJCZ3dGb0FVMkxWWGtXNkpuY2ZKQkxocHEwNG1EWEdNbnlvd0R3WURWUjBUQVFIL0JBVXdBd0VCCi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFLRzdGeW1KZnc4bmJCZkg3bDNuZzk4UGhTNy9LV08zRkN6TWwKRWUxeXpLOTFPM21QVTBaRWY2MEFINmM5YUtTNHJkbnU4NzJmL0FiNkNIQU1GVWwwaWx3NDU1cmpMTjgyeDM2Swo5cWNvTHRHZkpjWVkrdGZleEw1ekxGNHZUSExhMGFjWHNhY0owWWdEUjhsdytyMGZGMFZGQjdRUnNXU1dUYStOCldrL3o5QVFpMEdKSjdOaVl6UGFYalVPT1BPN1BZOHVHblN1MFpnTGVlelNkNXFmc0FTY0JTejUvYi9rd000WXcKVXBVSDk1d1RMbE1yRTZQVHNlYlZqMnRycWdOUStSV0szYnVMUThJTW85ME15aDRPbEw0cmRQZ3ZWa0FZSkJLVAozem03NEcvZWpMRHN2L2tHRzh2cmZ2MXZtb3RxNE9GeGY2UGhEUllBY1hBYnNvUzR6UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: webhook-service
      namespace: coralogix-operator-system
      path: /validate-coralogix-com-v1alpha1-outboundwebhook
  failurePolicy: Fail
  name: outboundwebhook.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - outboundwebhooks
  sideEffects: None
