---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-coralogix-com-v1alpha1-outboundwebhook
  failurePolicy: Fail
  name: voutboundwebhook.kb.io
  rules:
  - apiGroups:
    - coralogix.coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - outboundwebhooks
  sideEffects: None
