---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1alpha1-alertscheduler
  failurePolicy: Fail
  name: valertscheduler-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alertschedulers
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1alpha1-apikey
  failurePolicy: Fail
  name: vapikey-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - apikeys
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1alpha1-dashboard
  failurePolicy: Fail
  name: vdashboard-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dashboards
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1alpha1-outboundwebhook
  failurePolicy: Fail
  name: voutboundwebhook-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - outboundwebhooks
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1alpha1-rulegroup
  failurePolicy: Fail
  name: vrulegroup-v1alpha1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rulegroups
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-coralogix-com-v1beta1-alert
  failurePolicy: Fail
  name: valert-v1beta1.kb.io
  rules:
  - apiGroups:
    - coralogix.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - alerts
  sideEffects: None
