{{- if .Values.alerts.enabled }}
apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  name: {{ include "coralogixOperator.fullname" . }}-reconcile-error-high
  labels:
    {{ include "coralogixOperator.labels" . | nindent 4 }}
spec:
  name: {{ include "coralogixOperator.fullname" . }}-reconcile-error-high
  description: High reconcile error high - over 10% of reconciliations are failing, usually because of bad config, permission issues, or an upstream service outage.
  priority: p4
  entityLabels:
    {{- range $key, $value := .Values.alerts.alertReconcileErrorRatio.entityLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  alertType:
    metricThreshold:
      metricFilter:
        promql: |
          coralogix_operator:reconcile_errors_total:pod
      missingValues:
        minNonNullValuesPct: 0
      rules:
        - condition:
            threshold: "0.1"
            forOverPct: 100
            ofTheLast:
              specificValue: 10m
            conditionType: moreThan
{{- end }}
