{{- if .Values.alerts.enabled }}
apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
  {{ include "coralogixOperator.labels" . | nindent 4 }}
  name: coralogix-operator-many-crs-not-synced-alert
spec:
  name: CoralogixOperatorManyCrsNotSyncedAlert
  description: Fires when the ratio of RemoteUnsynced state is more than 5%, grouped by kind and namespace. This indicates a partial sync failure between Kubernetes and Coralogix for a specific resource type or namespace.
  priority: p3
  entityLabels:
    {{- range $key, $value := .Values.alerts.alert_crs_not_synced.entityLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  alertType:
    metricThreshold:
      metricFilter:
        promql: |
          count(cx_operator_resource_info{status="RemoteUnsynced"}) by (kind, namespace)/count(cx_operator_resource_info{}) by (kind, namespace)
      missingValues:
        minNonNullValuesPct: 0
      rules:
        - condition:
            threshold: "0.05" # 5% of the resources managed by the operator are in RemoteUnsynced state
            forOverPct: 100
            ofTheLast:
              specificValue: 5m
            conditionType: moreThan
  notificationGroup:
  {{- end }}