{{- if .Values.coralogixOperator.webhooks.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
  name: {{ include "coralogixOperator.fullname" . }}-serving-cert
spec:
  dnsNames:
    - {{ include "coralogixOperator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "coralogixOperator.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ include "coralogixOperator.fullname" . }}-webhook-cert
{{- end }}
