apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "coralogixOperator.fullname" . }}
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - coralogix.com
  resources:
  - alerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alerts/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - alerts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coralogix.com
  resources:
  - recordingrulegroupsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - recordingrulegroupsets/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - recordingrulegroupsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coralogix.com
  resources:
  - rulegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - rulegroups/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - rulegroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coralogix.com
  resources:
  - outboundwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - outboundwebhooks/finalizers
  verbs:
  - update
- apiGroups:
  - coralogix.com
  resources:
  - outboundwebhooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - prometheusrules
  - alertmanagerconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch