{{- if and .Values.coralogixOperator.webhooks.enabled .Values.issuer.create }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
  name: {{ include "coralogixOperator.fullname" . }}-selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}
