apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "coralogixOperator.fullname" . }}-metrics-reader
rules:
- apiGroups: [ "" ]
  resources:
    - services
    - endpoints
    - pods
  verbs:
    - get
    - list
    - watch
- nonResourceURLs:
    - "/metrics"
  verbs:
    - get
