{{- if and (.Values.secret.create) (not .Values.secret.secretKeyReference) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coralogixOperator.fullname" . }}
  {{- with .Values.secret.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  CORALOGIX_API_KEY: {{ .Values.secret.data.apiKey }}
{{- end -}}
