apiVersion: v1
kind: Service
metadata:
  name: {{ include "coralogixOperator.fullname" . }}
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    {{- include "coralogixOperator.selectorLabels" . | nindent 4 }}
