{{- if .Values.coralogixOperator.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coralogixOperator.fullname" . }}-webhook-service
  labels:
    {{- include "coralogixOperator.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "coralogixOperator.selectorLabels" . | nindent 4 }}
{{- end }}
