apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: config-example
  labels:
    alertmanagerConfig: example
    app.coralogix.com/track-alertmanger-config: "true"
spec:
  route:
    groupBy:
      - alertname
      - cluster
      - alert_group
      - job
      - namespace
      - severity
      - priority
    receiver: slack-default
    repeatInterval: 3h
    routes:
      - receiver: slack-general
        matchers:
          - matchType: "=~"
            name: slack_channel
            value: ".+"
        continue: true
      - receiver: opsgenie-general
        groupBy:
          - alertname
        matchers:
          - matchType: "=~"
            name: opsgenie_team
            value: ".+"
        repeatInterval: 4m
  receivers:
    - name: slack-general
      slackConfigs:
        - apiURL:
            name: "slack-webhook-secret" # Name of the Kubernetes Secret
            key: "webhook-url"          # Key in the Kubernetes Secret
    - name: opsgenie-general
      opsgenieConfigs:
        - sendResolved: true
          apiURL: https://api.opsgenie.com/v2/alerts
    - name: slack-default
      slackConfigs:
        - sendResolved: false
          apiURL:
            name: "slack-webhook-secret" # Name of the Kubernetes Secret
            key: "webhook-url"          # Key in the Kubernetes Secret