apiVersion: coralogix.com/v1alpha1
kind: Connector
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/instance: connector-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: eventbridge-sample
spec:
  name: eventbridge-sample
  description: This is a sample EventBridge connector
  type: eventBridge
  connectorConfig:
    fields:
      - fieldName: integrationId
        value: some-integration-id
