apiVersion: coralogix.com/v1alpha1
kind: Connector
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: generic-https-sample
spec:
  name: IAC testing
  description: This is the connector to use for Notification Center testing.
  connectorType:
    genericHttps:
      config:
        url: https://example.com
        method: post
        additionalHeaders: "{\"Content-Type\": \"application/json\"}"
        additionalBodyFields: "{\"text\": \"This is a generic HTTPS connector general message\"}"
