apiVersion: coralogix.com/v1alpha1
kind: Connector
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: slack-sample
spec:
  name: IAC testing
  description: This is the connector to use for Notification Center testing.
  connectorType:
    slack:
      commonFields:
        rawConfig:
          integration:
            backendRef:
              id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
          channel: general
          fallbackChannel: fallback_general
        structuredConfig:
          integration:
            backendRef:
              id: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
          channel: general
          fallbackChannel: fallback_general
      overrides:
        - entityType: alerts
          structuredConfig:
            channel: override
          rawConfig:
            channel: override
