# permissions for end users to view connectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: coralogix-connector-viewer-role
rules:
- apiGroups:
  - coralogix.com
  resources:
  - connectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - connectors/status
  verbs:
  - get
