# permissions for end users to edit alertschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: coralogix-alertscheduler-editor-role
rules:
- apiGroups:
  - coralogix.com
  resources:
  - alertschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - alertschedulers/status
  verbs:
  - get
