# permissions for end users to edit outboundwebhooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: outboundwebhook-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: coralogix-operator
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: outboundwebhook-editor-role
rules:
- apiGroups:
  - coralogix.coralogix.com
  resources:
  - outboundwebhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coralogix.com
  resources:
  - outboundwebhooks/status
  verbs:
  - get
