# Analytics alerts are in preview.
apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: analytics-threshold
spec:
  name: analytics-threshold alert example
  description: alert from k8s operator
  priority: p3
  # groupByKeys must be columns returned by the query.
  groupByKeys:
    - applicationname
  alertType:
    analyticsThreshold:
      dataprimeQuery:
        query: source logs | filter $m.severity == Severity.ERROR | groupby $l.applicationname aggregate count() as errors
      targetColumn: errors
      operator: moreThan
      timeframeMinutes: 30
      useRowsAsPermutations: true
      rules:
        - condition:
            threshold: "100"
          override:
            priority: p1
        - condition:
            threshold: "50"
          override:
            priority: p2
        - condition:
            threshold: "10.5"
          override:
            priority: p3
