apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret   # Name of the secret
  namespace: default           # Namespace where the secret is created
type: Opaque
data:
  webhook-url: aHR0cHM6Ly9zbGFjay5jb20vYXBpL2NoYXQucG9zdE1lc3NhZ2U=  # Base64 encoded API URL
---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  labels:
    app.coralogix.com/track-alertmanger-config: "true"
  name: resource-alert-routing
spec:
  route:
    groupBy: ['alertname', 'instance']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 3h
    receiver: 'default'
    routes:
      - matchers:
          - name: severity
            value: critical
        receiver: pagerduty-critical
      - matchers:
          - name: severity
            value: warning
        receiver: slack-warning
  receivers:
    - name: default
      webhookConfigs:
        - url: 'http://default-receiver.local'
    - name: opsgenie-critical
      opsgenieConfigs:
          - sendResolved: true
            apiURL: https://api.opsgenie.com/v2/alerts
    - name: slack-warning
      slackConfigs:
        - apiURL:
            name: "slack-webhook-secret" # Name of the Kubernetes Secret
            key: "webhook-url"          # Key in the Kubernetes Secret
---

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: example
    role: alert-rules
    app.coralogix.com/track-alerting-rules: "true"
    app.coralogix.com/managed-by-alertmanger-config: "true"
  name: prometheus-example-rules
spec:
  groups:
    - name: example.rules
      interval: "60s"
      rules:
        - alert: HighCPUUsage
          expr: group by (node, pod) sum(cpu_usage{pod=~"coralogix.*"})
          for: 5m
          annotations:
            description: "High CPU consumption for pod {{ $labels.pod }} 
            on instance {{ $labels.node }}."
          labels:
            severity: critical
            slack_channel: "#observability"
        - alert: HighMemoryUsage
          expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.2
          for: 10m
          labels:
            severity: warning
            team: dev
          annotations:
            summary: "High Memory usage detected on {{ $labels.instance }}"
            description: "Memory usage on instance {{ $labels.instance }} is above 80% for more than 10 minutes."

