apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: alert-sample
spec:
  # TODO(user): Add fields here
