// Code generated by MockGen. DO NOT EDIT.
// Source: recording-rules-groups-client.go
//
// Generated by this command:
//
//	mockgen -destination=../mock_clientset/mock_recordingrulesgroups-client.go -package=mock_clientset -source=recording-rules-groups-client.go RecordingRulesGroupsClientInterface
//
// Package mock_clientset is a generated GoMock package.
package mock_clientset

import (
	context "context"
	reflect "reflect"

	cxsdk "github.com/coralogix/coralogix-management-sdk/go"
	gomock "go.uber.org/mock/gomock"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// MockRecordingRulesGroupsClientInterface is a mock of RecordingRulesGroupsClientInterface interface.
type MockRecordingRulesGroupsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRecordingRulesGroupsClientInterfaceMockRecorder
}

// MockRecordingRulesGroupsClientInterfaceMockRecorder is the mock recorder for MockRecordingRulesGroupsClientInterface.
type MockRecordingRulesGroupsClientInterfaceMockRecorder struct {
	mock *MockRecordingRulesGroupsClientInterface
}

// NewMockRecordingRulesGroupsClientInterface creates a new mock instance.
func NewMockRecordingRulesGroupsClientInterface(ctrl *gomock.Controller) *MockRecordingRulesGroupsClientInterface {
	mock := &MockRecordingRulesGroupsClientInterface{ctrl: ctrl}
	mock.recorder = &MockRecordingRulesGroupsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordingRulesGroupsClientInterface) EXPECT() *MockRecordingRulesGroupsClientInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRecordingRulesGroupsClientInterface) Create(ctx context.Context, req *cxsdk.CreateRuleGroupSetRequest) (*cxsdk.CreateRuleGroupSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*cxsdk.CreateRuleGroupSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRecordingRulesGroupsClientInterfaceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRecordingRulesGroupsClientInterface)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockRecordingRulesGroupsClientInterface) Delete(ctx context.Context, req *cxsdk.DeleteRuleGroupSetRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockRecordingRulesGroupsClientInterfaceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRecordingRulesGroupsClientInterface)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockRecordingRulesGroupsClientInterface) Get(ctx context.Context, req *cxsdk.GetRuleGroupSetRequest) (*cxsdk.GetRuleGroupSetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(*cxsdk.GetRuleGroupSetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRecordingRulesGroupsClientInterfaceMockRecorder) Get(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRecordingRulesGroupsClientInterface)(nil).Get), ctx, req)
}

// Update mocks base method.
func (m *MockRecordingRulesGroupsClientInterface) Update(ctx context.Context, req *cxsdk.UpdateRuleGroupSetRequest) (*emptypb.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*emptypb.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRecordingRulesGroupsClientInterfaceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRecordingRulesGroupsClientInterface)(nil).Update), ctx, req)
}
