// Code generated by MockGen. DO NOT EDIT.
// Source: teams-client.go
//
// Generated by this command:
//
//	mockgen -destination=../mock_clientset/mock_teams-client.go -package=mock_clientset -source=teams-client.go TeamsClientInterface
//
// Package mock_clientset is a generated GoMock package.
package mock_clientset

import (
	context "context"
	reflect "reflect"

	cxsdk "github.com/coralogix/coralogix-management-sdk/go"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamsClientInterface is a mock of TeamsClientInterface interface.
type MockTeamsClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsClientInterfaceMockRecorder
}

// MockTeamsClientInterfaceMockRecorder is the mock recorder for MockTeamsClientInterface.
type MockTeamsClientInterfaceMockRecorder struct {
	mock *MockTeamsClientInterface
}

// NewMockTeamsClientInterface creates a new mock instance.
func NewMockTeamsClientInterface(ctrl *gomock.Controller) *MockTeamsClientInterface {
	mock := &MockTeamsClientInterface{ctrl: ctrl}
	mock.recorder = &MockTeamsClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsClientInterface) EXPECT() *MockTeamsClientInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamsClientInterface) Create(ctx context.Context, req *cxsdk.CreateTeamInOrgRequest) (*cxsdk.CreateTeamInOrgResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*cxsdk.CreateTeamInOrgResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamsClientInterfaceMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamsClientInterface)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockTeamsClientInterface) Delete(ctx context.Context, req *cxsdk.DeleteTeamRequest) (*cxsdk.DeleteTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, req)
	ret0, _ := ret[0].(*cxsdk.DeleteTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTeamsClientInterfaceMockRecorder) Delete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTeamsClientInterface)(nil).Delete), ctx, req)
}

// Get mocks base method.
func (m *MockTeamsClientInterface) Get(ctx context.Context, req *cxsdk.GetTeamRequest) (*cxsdk.GetTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, req)
	ret0, _ := ret[0].(*cxsdk.GetTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamsClientInterfaceMockRecorder) Get(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamsClientInterface)(nil).Get), ctx, req)
}

// Update mocks base method.
func (m *MockTeamsClientInterface) Update(ctx context.Context, req *cxsdk.UpdateTeamRequest) (*cxsdk.UpdateTeamResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, req)
	ret0, _ := ret[0].(*cxsdk.UpdateTeamResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTeamsClientInterfaceMockRecorder) Update(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTeamsClientInterface)(nil).Update), ctx, req)
}
