apiVersion: coralogix.com/v1alpha1
kind: Integration
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/instance: integration-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: crowd-strike-collector
spec:
  integrationKey: crowd-strike-collector
  version: 0.0.1
  parameters:
    IntegrationName: CrowdStrike
    ApplicationName: <ApplicationName>
    SubsystemName: CrowdStrike
    ClientId: <ClientId>
    ClientSecret: <ClientSecret>
