apiVersion: coralogix.com/v1alpha1
kind: ApiKey
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: user-key-sample
spec:
  name: user-key-sample
  owner:
    userId: aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee
  presets:
    - APM
  permissions:
    - ALERTS-MAP:READ
