apiVersion: coralogix.com/v1alpha1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: standard-immediate
spec:
  name: standard immediate example
  description: alert from k8s operator
  severity: Info
  notificationGroups:
    - notifications:
        - notifyOn: TriggeredOnly
          integrationName: slack-webhook
          retriggeringPeriodMinutes: 60
  alertType:
    standard:
      filters:
        searchQuery: remote_addr_enriched:/.*/
        applications: [ "filter:contains:nginx" ]
        subsystems: [ "filter:startsWith:subsystem-name" ]
        severities: [ "Warning", "Info" ]
      conditions:
        alertWhen: Immediately
