{{- if .Values.alerts.enabled }}
apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  name: {{ include "coralogixOperator.fullname" . }}-reconcile-error-high
  labels:
    {{ include "coralogixOperator.labels" . | nindent 4 }}
spec:
  name: {{ include "coralogixOperator.fullname" . }}-reconcile-error-high
  description: High reconcile error - over 10% of reconciliations are failing.
  priority: p4
  entityLabels:
    {{- range $key, $value := .Values.alerts.alertReconcileErrorHigh.entityLabels }}
      {{ $key }}: {{ $value }}
    {{- end }}
  alertType:
    metricThreshold:
      metricFilter:
        promql: |
          {{ include "coralogixOperator.fullname" . }}:reconcile_errors_rate:pod / {{ include "coralogixOperator.fullname" . }}:reconcile_total:pod
      missingValues:
        minNonNullValuesPct: 0
      rules:
        - condition:
            threshold: "0.1"
            forOverPct: 100
            ofTheLast:
              specificValue: 10m
            conditionType: moreThan
{{- end }}
