apiVersion: coralogix.com/v1alpha1
kind: GlobalRouter
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/instance: global-router-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: global-router-sample
spec:
  name: global-router-sample
  description: This is a sample global router
  entityType: alerts
  fallback:
    - connector:
        resourceRef:
          name: slack-sample
      preset:
        resourceRef:
          name: slack-sample
  rules:
    - name: first rule
      condition: alertDef.priority == P1
      targets:
        - connector:
            resourceRef:
              name: slack-sample
          preset:
            resourceRef:
              name: slack-sample
        - connector:
            resourceRef:
              name: slack-sample
          preset:
            backendRef:
              id: a1db725b-7e35-41c1-8c01-d9ab46f9a2db # can be user facing id once backend supports it
    - name: second rule
      condition: alertDef.priority == P2
      targets:
        - connector:
            resourceRef:
              name: slack-sample
          preset:
            resourceRef:
              name: slack-sample
        - connector:
            resourceRef:
              name: slack-sample
          preset:
            backendRef:
              id: a1db725b-7e35-41c1-8c01-d9ab46f9a2db # can be user facing id once backend supports it
