//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AwsEventBridge) DeepCopyInto(out *AwsEventBridge) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AwsEventBridge.
func (in *AwsEventBridge) DeepCopy() *AwsEventBridge {
	if in == nil {
		return nil
	}
	out := new(AwsEventBridge)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Demisto) DeepCopyInto(out *Demisto) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Demisto.
func (in *Demisto) DeepCopy() *Demisto {
	if in == nil {
		return nil
	}
	out := new(Demisto)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EmailGroup) DeepCopyInto(out *EmailGroup) {
	*out = *in
	if in.EmailAddresses != nil {
		in, out := &in.EmailAddresses, &out.EmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EmailGroup.
func (in *EmailGroup) DeepCopy() *EmailGroup {
	if in == nil {
		return nil
	}
	out := new(EmailGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericWebhook) DeepCopyInto(out *GenericWebhook) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericWebhook.
func (in *GenericWebhook) DeepCopy() *GenericWebhook {
	if in == nil {
		return nil
	}
	out := new(GenericWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericWebhookStatus) DeepCopyInto(out *GenericWebhookStatus) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Payload != nil {
		in, out := &in.Payload, &out.Payload
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericWebhookStatus.
func (in *GenericWebhookStatus) DeepCopy() *GenericWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(GenericWebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Jira) DeepCopyInto(out *Jira) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Jira.
func (in *Jira) DeepCopy() *Jira {
	if in == nil {
		return nil
	}
	out := new(Jira)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MicrosoftTeams) DeepCopyInto(out *MicrosoftTeams) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MicrosoftTeams.
func (in *MicrosoftTeams) DeepCopy() *MicrosoftTeams {
	if in == nil {
		return nil
	}
	out := new(MicrosoftTeams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Opsgenie) DeepCopyInto(out *Opsgenie) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Opsgenie.
func (in *Opsgenie) DeepCopy() *Opsgenie {
	if in == nil {
		return nil
	}
	out := new(Opsgenie)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundWebhook) DeepCopyInto(out *OutboundWebhook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundWebhook.
func (in *OutboundWebhook) DeepCopy() *OutboundWebhook {
	if in == nil {
		return nil
	}
	out := new(OutboundWebhook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutboundWebhook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundWebhookList) DeepCopyInto(out *OutboundWebhookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OutboundWebhook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundWebhookList.
func (in *OutboundWebhookList) DeepCopy() *OutboundWebhookList {
	if in == nil {
		return nil
	}
	out := new(OutboundWebhookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OutboundWebhookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundWebhookSpec) DeepCopyInto(out *OutboundWebhookSpec) {
	*out = *in
	in.OutboundWebhookType.DeepCopyInto(&out.OutboundWebhookType)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundWebhookSpec.
func (in *OutboundWebhookSpec) DeepCopy() *OutboundWebhookSpec {
	if in == nil {
		return nil
	}
	out := new(OutboundWebhookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundWebhookStatus) DeepCopyInto(out *OutboundWebhookStatus) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ExternalID != nil {
		in, out := &in.ExternalID, &out.ExternalID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundWebhookStatus.
func (in *OutboundWebhookStatus) DeepCopy() *OutboundWebhookStatus {
	if in == nil {
		return nil
	}
	out := new(OutboundWebhookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutboundWebhookType) DeepCopyInto(out *OutboundWebhookType) {
	*out = *in
	if in.GenericWebhook != nil {
		in, out := &in.GenericWebhook, &out.GenericWebhook
		*out = new(GenericWebhook)
		(*in).DeepCopyInto(*out)
	}
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(Slack)
		(*in).DeepCopyInto(*out)
	}
	if in.PagerDuty != nil {
		in, out := &in.PagerDuty, &out.PagerDuty
		*out = new(PagerDuty)
		**out = **in
	}
	if in.SendLog != nil {
		in, out := &in.SendLog, &out.SendLog
		*out = new(SendLog)
		**out = **in
	}
	if in.EmailGroup != nil {
		in, out := &in.EmailGroup, &out.EmailGroup
		*out = new(EmailGroup)
		(*in).DeepCopyInto(*out)
	}
	if in.MicrosoftTeams != nil {
		in, out := &in.MicrosoftTeams, &out.MicrosoftTeams
		*out = new(MicrosoftTeams)
		**out = **in
	}
	if in.Jira != nil {
		in, out := &in.Jira, &out.Jira
		*out = new(Jira)
		**out = **in
	}
	if in.Opsgenie != nil {
		in, out := &in.Opsgenie, &out.Opsgenie
		*out = new(Opsgenie)
		**out = **in
	}
	if in.Demisto != nil {
		in, out := &in.Demisto, &out.Demisto
		*out = new(Demisto)
		**out = **in
	}
	if in.AwsEventBridge != nil {
		in, out := &in.AwsEventBridge, &out.AwsEventBridge
		*out = new(AwsEventBridge)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutboundWebhookType.
func (in *OutboundWebhookType) DeepCopy() *OutboundWebhookType {
	if in == nil {
		return nil
	}
	out := new(OutboundWebhookType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PagerDuty) DeepCopyInto(out *PagerDuty) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PagerDuty.
func (in *PagerDuty) DeepCopy() *PagerDuty {
	if in == nil {
		return nil
	}
	out := new(PagerDuty)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SendLog) DeepCopyInto(out *SendLog) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SendLog.
func (in *SendLog) DeepCopy() *SendLog {
	if in == nil {
		return nil
	}
	out := new(SendLog)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SendLogStatus) DeepCopyInto(out *SendLogStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SendLogStatus.
func (in *SendLogStatus) DeepCopy() *SendLogStatus {
	if in == nil {
		return nil
	}
	out := new(SendLogStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Slack) DeepCopyInto(out *Slack) {
	*out = *in
	if in.Digests != nil {
		in, out := &in.Digests, &out.Digests
		*out = make([]SlackConfigDigest, len(*in))
		copy(*out, *in)
	}
	if in.Attachments != nil {
		in, out := &in.Attachments, &out.Attachments
		*out = make([]SlackConfigAttachment, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Slack.
func (in *Slack) DeepCopy() *Slack {
	if in == nil {
		return nil
	}
	out := new(Slack)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfigAttachment) DeepCopyInto(out *SlackConfigAttachment) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfigAttachment.
func (in *SlackConfigAttachment) DeepCopy() *SlackConfigAttachment {
	if in == nil {
		return nil
	}
	out := new(SlackConfigAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SlackConfigDigest) DeepCopyInto(out *SlackConfigDigest) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SlackConfigDigest.
func (in *SlackConfigDigest) DeepCopy() *SlackConfigDigest {
	if in == nil {
		return nil
	}
	out := new(SlackConfigDigest)
	in.DeepCopyInto(out)
	return out
}
