apiVersion: coralogix.com/v1alpha1
kind: Preset
metadata:
  labels:
    app.kubernetes.io/name: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
  name: generic-https-sample
spec:
  name: Generic Https Preset
  description: A preset for Https integration
  entityType: alerts
  parentId: preset_system_generic_https_alerts_empty
  connectorType:
    genericHttps:
      general:
        fields:
          headers: "{\"Content-Type\": \"application/json\"}"
          body: "{\"text\": \"This is a generic HTTPS preset general message\"}"
      overrides:
        - entitySubType: metricThresholdMoreThanTriggered
          fields:
            headers: "{\"Content-Type\": \"override\"}"
        - entitySubType: metricThresholdLessThanTriggered
          fields:
            body: "{\"text\": \"This is an overridden preset for entitySubType metricThresholdLessThanTriggered\"}"
        - entitySubType: metricThresholdMoreThanOrEqualsTriggered
          fields:
            headers: "{\"Content-Type\": \"override\"}"
            body: "{\"text\": \"This is an overridden preset for entitySubType metricThresholdMoreThanTriggered\"}"
