name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**"

jobs:
  build:
    env:
      GO111MODULE: on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: 1.20.x
      - name: Run build
        run: make build
