name: Container
on:
  pull_request:
    paths-ignore:
      - "charts/**"
  push:
    branches:
      - "main"
    tags:
      - "v*"
    paths-ignore:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REGISTRY: coralogixrepo/coralogix-operator

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.repository == 'coralogix/coralogix-operator' && github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ${{ env.DOCKERHUB_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Fetch latest release version
        id: fetch-latest-release
        uses: reloc8/action-latest-release-version@1.0.0

      - name: Build And Push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.repository == 'coralogix/coralogix-operator' && github.event_name != 'pull_request'}}
          tags: |
            ${{ steps.meta.outputs.tags }}
            coralogix/coralogix-operator:${{ steps.fetch-latest-release.outputs.latest-release }}
            coralogix/coralogix-operator:latest
