name: Container
on:
  pull_request:
    paths-ignore:
      - "charts/**"
  push:
    branches:
      - "main"
      - "release-*"
    tags:
      - "v*"
    paths-ignore:
      - "charts/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKERHUB_REGISTRY: coralogixrepo/coralogix-operator

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.repository == 'coralogix/coralogix-operator' && github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e
        with:
          images: ${{ env.DOCKERHUB_REGISTRY }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Determine if latest based on tag (vX.Y.0)
        run: |
          TAG="${{ github.ref_name }}"
          PATCH=$(echo "${TAG#v}" | cut -d. -f3)
          if [ "$PATCH" = "0" ]; then
            echo "TAG_LATEST=true" >> $GITHUB_ENV
          else
            echo "TAG_LATEST=false" >> $GITHUB_ENV
          fi

      - name: Build And Push
        uses: docker/build-push-action@v2.8.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.DOCKERHUB_REGISTRY }}:${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.sha }}
            ${{ env.TAG_LATEST == 'true' && format('{0}:latest', env.DOCKERHUB_REGISTRY) || '' }}
