name: generate

on:
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**"

jobs:
  check-docs:
    name: Check generated files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      - name: Generate docs and manifests
        run: |
          make generate
          make manifests
          make generate-api-docs
      - name: Check for changes
        run: |
          if ! git diff --exit-code; then
            echo "Some files are out of date. Please run the following commands and commit the changes:"
            echo "    make generate-api-docs"
            echo "    make generate"
            echo "    make manifests"
            exit 1
          fi
