name: update chart version and open pr
on:
  push:
    tags:
      - "v*"

jobs:
  update-chart-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update Chart Version
        run: |
            TAG="${{ github.ref_name }}"
            VERSION="${TAG#v}"

            sed -i "s/^appVersion:.*/appVersion: $VERSION/" charts/coralogix-operator/Chart.yaml
            sed -i "s/^version:.*/version: $VERSION/" charts/coralogix-operator/Chart.yaml


      - name: Update Chart version in Documentation
        run: make helm-sync-docs

      - name: Extract Release Branch from Tag
        run: |
          TAG="${{ github.ref_name }}"
          VERSION="${TAG#v}"
          echo "RELEASE_BRANCH=$(echo "$VERSION" | cut -d. -f1,2)" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Bump version and update appVersion in Chart.yaml"
          title: "Bump version and update appVersion in Chart.yaml"
          base: release-${{ env.RELEASE_BRANCH }}
          branch: update-chart-version-${{ github.ref_name }}
          add-paths: |
            charts/coralogix-operator/Chart.yaml
            charts/coralogix-operator/README.md
          body: |
            This pull request bumps the version and updates the appVersion in Chart.yaml to match the tag.
