name: helm-lint-and-test

on:
  pull_request:
    paths:
      - "charts/coralogix-operator/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check if Helm CRDs templates are updated
        run: |
          make helm-check-crd-version
