name: helm-e2e-tests
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
      - release-*
  pull_request:
    branches:
      - main
      - release-*
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      IMG_REPO: coralogix-operator-image
      IMG_TAG: 0.0.1
      CORALOGIX_REGION: ${{ secrets.CORALOGIX_REGION }}
      CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      LOGS_BUCKET: ${{ secrets.LOGS_BUCKET }}
      METRICS_BUCKET: ${{ secrets.METRICS_BUCKET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the controller-manager Docker image
        run: |
          make docker-build IMG=${{ env.IMG_REPO }}:v${{ env.IMG_TAG }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Load the controller-manager image into Kind
        run: |
          kind load docker-image ${{ env.IMG_REPO }}:v${{ env.IMG_TAG }} --name chart-testing
      - name: Install Prometheus Operator CRDs
        run: |
          make install-prometheus-crds
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Install Coralogix Operator using Helm
        run: |
          helm install coralogix-operator ./charts/coralogix-operator \
            --namespace coralogix-operator-system \
            --create-namespace \
            --set secret.data.apiKey="${{ secrets.CORALOGIX_API_KEY }}" \
            --set coralogixOperator.image.repository="${{ env.IMG_REPO }}" \
            --set coralogixOperator.image.tag="${{ env.IMG_TAG }}" \
            --set coralogixOperator.region="${{ secrets.CORALOGIX_REGION }}" \
            --set coralogixOperator.reconcileIntervalSeconds.scope=30
      - name: Run e2e Tests
        run: |
          make e2e-tests
      - name: Collect Operator Logs
        if: always()
        run: |
          scripts/collect-logs.sh
