name: integration-tests
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**"
jobs:
  tests:
    name: Tests
    env:
      IMG: tests.com/coralogix-operator:v0.0.1
      CORALOGIX_REGION: ${{ secrets.CORALOGIX_REGION }}
      CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Build the controller-manager Docker image
          run: |
            make docker-build
        - name: Create k8s Kind Cluster
          uses: helm/kind-action@v1.4.0
        - name: Load the controller-manager image into Kind
          run: |
            kind load docker-image ${{ env.IMG }} --name chart-testing
        - name: Deploy the controller-manager
          run: |
            make deploy
        - name: Run Integration Tests
          run: |
            make integration-tests