name: integration-tests
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**"
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      IMG: coralogix-operator:latest
      CORALOGIX_REGION: ${{ secrets.CORALOGIX_REGION }}
      CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the controller-manager Docker image
        run: |
           make docker-build IMG=${IMG}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
      - name: Load the controller-manager image into Kind
        run: |
          kind load docker-image ${{ env.IMG }} .
      - name: Deploy the controller-manager
        run: |
          make deploy IMG=${IMG}
      - name: Install kuttl
        run: |
          curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.12.1/kubectl-kuttl_0.12.1_linux_x86_64
          chmod +x /usr/local/bin/kubectl-kuttl
      - name: Run Integration Tests
        run: |
          make integration-tests