name: integration-tests
on:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths-ignore:
      - "charts/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "charts/**"
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          version: v0.11.1  # Specify the version of Kind you need

      - name: Build Operator Docker Image
        run: |
          docker build --build-arg LDFLAGS="-X google.golang.org/protobuf/reflect/protoregistry.conflictPolicy=warn" -t coralogix-operator-image:latest .

      - name: Load Docker Image into Kind
        run: |
          kind load docker-image coralogix-operator-image:latest

      - name: Install kuttl
        run: |
          curl -Lo /usr/local/bin/kubectl-kuttl https://github.com/kudobuilder/kuttl/releases/download/v0.12.1/kubectl-kuttl_0.12.1_linux_x86_64
          chmod +x /usr/local/bin/kubectl-kuttl

      - name: Install CRDs
        run: make install

      - name: Deploy Operator
        run: |
          make deploy IMG=coralogix-operator-image:latest

      - name: Wait for Operator to be Running
        run: |
          kubectl wait --for=condition=available --timeout=120s deployment/controller-manager -n coralogix-operator-system

      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
        with:
          go-version: 1.22.x

      - name: Running Integration Tests
        env:
          CORALOGIX_REGION: ${{ secrets.CORALOGIX_REGION }}
          CORALOGIX_API_KEY: ${{ secrets.CORALOGIX_API_KEY }}
        run: |
          make integration-tests
