name: unit-tests
on:
  pull_request:
    paths-ignore:
      - "charts/**"
  push:
    branches:
      - 'main'
    paths-ignore:
      - "charts/**"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.4.0
    - name: Install CRDs
      run: make install
    - run: make unit-tests
    - name: Patch Coverage
      uses: seriousben/go-patch-cover-action@v1
      with:
        version: v0.2.0
        coverage_filename: cover.out