apiVersion: coralogix.com/v1alpha1
kind: OutboundWebhook
metadata:
  labels:
    app.kubernetes.io/name: outboundwebhook
    app.kubernetes.io/instance: outboundwebhook-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: microsoft-teams-workflow-webhook
spec:
  name: microsoft-teams-workflow-webhook
  outboundWebhookType:
    microsoftTeamsWorkflow:
      url: "https://xyxz.webhook.office.com/?q=operator-sample"
